# Generated by Django 3.0.6 on 2020-05-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200524_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='Post_id',
            new_name='post_id',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.CharField(default='', max_length=500),
        ),
    ]
