# Generated by Django 3.0.6 on 2020-05-24 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200524_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='thumbnail',
            new_name='image',
        ),
    ]
